baseURL = "https://blog.cn-sz.eu/"
DefaultContentLanguage = "de" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "de-de"
title = "Mein Schmierzettel"
copyright = "Christian Schnitz"
theme = "diary"
publishDir = "docs"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "news, diary, whatever"
enableGitalk = true


# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Schmierzettel" # will set 'og:site_name'
description = "Mein privater Schmierzettel"  # will set 'og:description'

[params.gitalk]
  owner = "cnszde"
  repo = "blog"
  client_id = "0cd746c43ae6126d4da9"
  client_secret = "d6b617669b60126571ad7ff53a50b95f3009ea47"
[taxonomies]
   tag = "tags"
   category = "categories"



[[menu.main]]
url = "/categories"
name = "Kategorie"
weight = 1
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 3

